host: 0.0.0.0
port: 8080
log:
  level: info
  path: ./logs
jwt:
  secret: hfjtSdYL6j!Ts$uD
  expire: 3600
db:
  host: localhost
  port: 3306
  user: test
  password: test
  name: test
baseURL: "https://your-domain.com" # 这里设置基础URL
