version: '3'

services:
  app:
    image: bearyin/vmq
    ports:
      - "47110:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
    depends_on:
      - sql
    command: [
      "sh",
      "-c",
      "cd /app && /app/vmq"
    ]
  sql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vmq
      MYSQL_USER: vmq
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
