name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]  # 监听所有标签的推送
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        docker build . --file Dockerfile --tag my-image-name:$TAG_NAME
