name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]  # 监听所有标签的推送

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG_NAME=${GITHUB_REF#refs/tags/}
        else
          TAG_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's|/|-|g')
          TAG_NAME=${TAG_NAME}-$(date +%Y%m%d%H%M%S)
        fi
        echo "Docker tag: $TAG_NAME"
        docker build . --file Dockerfile --tag my-image-name:$TAG_NAME
